### ISSUE TITLE
서버 증설에 따른 배포문제

### ISSUE THREAD

**Issue by JunHyeok96** [jerry-ljh/Musinsa-Watcher#66]
기존의 s3, Aws CodeDeploy를 통한 배포는 ec2에서는 쉽게 배포그룹을 설정할 수 있지만 다른 클라우드와 섞어 쓸 때는 사용이 불가합니다.  CD방식에 변경이 필요합니다.
![image](https://user-images.githubusercontent.com/52908154/103128492-e5f74580-46d8-11eb-896c-18a2c41fd6c9.png)

**Comment by JunHyeok96** [comment]
![image](https://user-images.githubusercontent.com/52908154/103128498-edb6ea00-46d8-11eb-82a9-931d5bfaa0bb.png)
도커를 활용하는 방식으로 바꿨습니다. 
빌드가 완료되면 docker hub에 이미지를 전송하고 scp를 이용해 각 서버에 배포 스크립트를 전달합니다. 그 후, ssh를 사용하여 배포스크립트를 실행하는 방식으로 배포가 진행됩니다.

**Comment by jerry-ljh** [comment]
1
